name: Bug Report
description: File a bug report to help us improve ugit
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run `ugit init`
        2. Add a file with `ugit add file.txt`
        3. Try to commit with `ugit commit -m "test"`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste the complete error message or output.
      render: shell
      placeholder: Paste error output here...

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.9.6, 3.11.2"
    validations:
      required: true

  - type: input
    id: ugit-version
    attributes:
      label: ugit Version
      description: What version of ugit are you using?
      placeholder: "e.g., 0.1.0, main branch"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, logs, or related issues.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you have done the following before submitting this bug report.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have included all the required information above
          required: true
        - label: I can reproduce this issue consistently
          required: true
        - label: I have tested this with the latest version of ugit
          required: false