blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/night-slayer18/ugit/tree/main/docs
    about: Check our comprehensive documentation for guides and examples
  - name: 💬 Discussions
    url: https://github.com/night-slayer18/ugit/discussions
    about: Ask questions and discuss ugit with the community
  - name: 🔒 Security Issues
    url: https://github.com/night-slayer18/ugit/security/advisories/new
    about: Report security vulnerabilities privately